# Generated by Django 5.2.3 on 2025-07-03 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_contactrequest_service_technology_testimonial_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Testimonial',
        ),
        migrations.AddField(
            model_name='contactrequest',
            name='files',
            field=models.FileField(blank=True, null=True, upload_to='contact_uploads/'),
        ),
        migrations.AddField(
            model_name='contactrequest',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contactrequest',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='contactrequest',
            name='terms_accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='service',
            name='icon_class',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='technology',
            name='icon_class',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='contactrequest',
            name='company',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
